### ISSUE TITLE
Error while running the site of fedora

### ISSUE THREAD

**Issue by dost4frnd** [electron/electronjs.org#1007]
I am getting following error while running the site:

[nodemon] 1.12.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node server.js`
app running on 5000
[Browsersync] Access URLs:
 -------------------------------------
          UI: http://localhost:3001
 -------------------------------------
 UI External: http://192.168.1.10:3001
 -------------------------------------
[Browsersync] Watching files...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /home/devesh/Downloads/setups_electron/electronjs.org/node_modules/electron-api-historian/electron/vendor/boto/boto/sdb ENOSPC
    at _errnoException (util.js:1024:11)
    at FSWatcher.start (fs.js:1374:19)
    at Object.fs.watch (fs.js:1400:11)
    at createFsWatchInstance (/home/devesh/Downloads/setups_electron/electronjs.org/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/devesh/Downloads/setups_electron/electronjs.org/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/devesh/Downloads/setups_electron/electronjs.org/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/devesh/Downloads/setups_electron/electronjs.org/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/devesh/Downloads/setups_electron/electronjs.org/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/devesh/Downloads/setups_electron/electronjs.org/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by vanessayuenn** [comment]
@dost4frnd `ENOSPC` means there's no more space on the drive. A quick search pointed me to this comment https://github.com/remy/nodemon/issues/1152#issuecomment-349939269; can you try the proposed solution there?

**Comment by zeke** [comment]
@dost4frnd I'm going to close this but feel free to comment if you are still experiencing this issue.
