### ISSUE TITLE
BrowserView example code from docs doesn't work

### ISSUE THREAD

**Issue by waffln** [electron/electronjs.org#2188]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.3
* **Operating System** (Platform and Version):
  * Windows 10 (1803)

### Expected Behavior
I expected the example to work. Not much more i can type here.

### Actual behavior
I received this error:
` App threw an error during load
Error: Cannot create BrowserWindow before app is ready
    at Object.<anonymous> (C:\Users\waffeln\Fast-Git\SmashScoreBoard\test.js:4:11)
    at Object.<anonymous> (C:\Users\waffeln\Fast-Git\SmashScoreBoard\test.js:17:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (C:\Users\waffeln\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:119:12)
    at Object.<anonymous> (C:\Users\waffeln\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:164:5)
    at Object.<anonymous> (C:\Users\waffeln\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:204:3)`

### To Reproduce
Simply copy the example code to a fresh JavaScript file and run it using `electron file.js`

**Comment by MarshallOfSound** [comment]
@waffln This has come up before and those code samples aren't designed to be fully functioning applications / launchable.  They are examples of how to use the APIs and are not intended to function in isolation.

If you want some easy end-to-end demos I'd recommend the demos that are built in to [Electron Fiddle](https://github.com/electron/fiddle) or [Electron API Demos](https://github.com/electron/electron-api-demos)

**Comment by MarshallOfSound** [comment]
In this case what you've run in to is `BrowserWindow`'s can't be constructed before the app `ready` event (as the error message indicates)

**Comment by waffln** [comment]
Ah okay, i didn't know they are not required to work on their own.
I don't need this code to work, i just browsed through the docs, tried this code and when it failed i thought i should make an issue so that other people won't have the same problem.
Thanks for clarifying.
