### ISSUE TITLE
App crash when running dev

### ISSUE THREAD

**Issue by BrRoman** [electron/electronjs.org#3075]
Entirely new on Electron and Node, I would be glad if you could tell me in which direction I have to search to fix my problem.
I try and run locally electronjs.org, but after a few seconds, I get this error:
```
fr_romain@frereromain:/media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org$ npm run dev

> electronjs.org@2.0.0 dev /media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org
> cross-env NODE_PATH=. NODE_ENV=development nodemon server.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,yml
[nodemon] starting `node server.js`
Dev app detected; compiling JS and CSS in memory
(node:3499) Warning: N-API is an experimental feature and could change at any time.
app running on 5000
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch /media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org/node_modules/browserify/test/bundle_external ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleDir (/media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:429:19)
    at FSWatcher.<anonymous> (/media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:477:19)
    at FSWatcher.<anonymous> (/media/fr_romain/DATA/Documents/Informatique/Prog/forks/electronjs.org/node_modules/browser-sync/node_modules/chokidar/lib/nodefs-handler.js:482:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
[nodemon] app crashed - waiting for file changes before starting...
```
Previous steps (installation juste this morning) seem to have worked fine.
I'm on Ubuntu 18.04.
Thanks in advance for your answer.

**Comment by BrRoman** [comment]
Upgraded to Node V10 (`nvm install v10`).
Increased amount of inotify watchers (https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc).
Now everything works fine.

Thanks a lot for this repo.
