### ISSUE TITLE
Intermittent TLS ECONNRESET when downloading headers from electronjs.org

### ISSUE THREAD

**Issue by lissyx** [electron/electronjs.org#3508]
Hello,

We have some CI setup in place that for a few weeks now intermittently fails on our Windows builds with `ECONNRESET`. This happens during some ElectronJS native module compilation, when fetching the headers from e.g., https://electronjs.org/headers/v5.0.13/node-v5.0.13-headers.tar.gz

Other versions exposes the issue as well, and we obiously can't reproduce the issue locally.

it does happens intermittently, but enough that it is a pain to deal with. We had no issue for several month in a raw, and as of today, only Windows CI runs on AWS, all Linux builds have moved to GCP, so we can't really tell if it's a Windows-level thing or an AWS-network thing.

Some of the regions / IPs:
```
[taskcluster 2020-02-06T14:08:33.117Z]     "public-ipv4": "35.175.120.155",
[taskcluster 2020-02-06T14:08:33.117Z]     "region": "us-east-1"
[taskcluster 2020-02-06T14:39:38.535Z]     "public-ipv4": "54.183.238.11",
[taskcluster 2020-02-06T14:39:38.535Z]     "region": "us-west-1"
[taskcluster 2020-02-06T11:36:18.695Z]     "public-ipv4": "54.175.79.12",
[taskcluster 2020-02-06T11:36:18.695Z]     "region": "us-east-1"
[taskcluster 2020-02-06T11:36:17.416Z]     "public-ipv4": "3.85.205.143",
[taskcluster 2020-02-06T11:36:17.416Z]     "region": "us-east-1"
[taskcluster 2020-02-05T18:15:22.277Z]     "public-ipv4": "3.228.21.46",
[taskcluster 2020-02-05T18:15:22.277Z]     "region": "us-east-1"
[taskcluster 2020-02-05T18:15:21.441Z]     "public-ipv4": "35.153.156.250",
[taskcluster 2020-02-05T18:15:21.441Z]     "region": "us-east-1"
[taskcluster 2020-02-05T18:15:22.542Z]     "public-ipv4": "100.26.182.3",
[taskcluster 2020-02-05T18:15:22.542Z]     "region": "us-east-1"
[taskcluster 2020-02-06T11:25:55.034Z]     "public-ipv4": "34.229.113.242",
[taskcluster 2020-02-06T11:25:55.034Z]     "region": "us-east-1"
[taskcluster 2020-02-05T15:42:11.421Z]     "public-ipv4": "34.201.30.72",
[taskcluster 2020-02-05T15:42:11.421Z]     "region": "us-east-1"
```

Some example of log showing the failure:
```
gyp verb get node dir compiling against --target node version: 5.0.13
gyp verb command install [ '5.0.13' ]
gyp verb download using dist-url https://electronjs.org/headers
gyp verb install input version string "5.0.13"
gyp verb install installing version: 5.0.13
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 5.0.13
gyp verb ensuring nodedir is created C:\Users\task_1580917296\.node-gyp\5.0.13
gyp verb created nodedir C:\Users\task_1580917296\.node-gyp\5.0.13
gyp http GET https://electronjs.org/headers/v5.0.13/node-v5.0.13-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp verb command remove [ '5.0.13' ]
gyp verb remove using node-gyp dir: C:\Users\task_1580917296\.node-gyp
gyp verb remove removing target version: 5.0.13
gyp verb remove removing development files for version: 5.0.13
gyp ERR! configure error 
gyp ERR! stack Error: read ECONNRESET
gyp ERR! stack     at TLSWrap.onread (net.js:622:25)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\builds\\tc-workdir\\DeepSpeech\\ds\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--runtime=electron" "--target=5.0.13" "--disturl=https://electronjs.org/headers" "--loglevel=verbose" "--module=C:\\builds\\tc-workdir\\DeepSpeech\\ds\\native_client\\javascript\\lib\\binding\\v0.7.0-alpha.1\\win32-x64\\electron-v5.0\\deepspeech.node" "--module_name=deepspeech" "--module_path=C:\\builds\\tc-workdir\\DeepSpeech\\ds\\native_client\\javascript\\lib\\binding\\v0.7.0-alpha.1\\win32-x64\\electron-v5.0" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=electron-v5.0"
gyp ERR! cwd C:\builds\tc-workdir\DeepSpeech\ds\native_client\javascript
gyp ERR! node -v v8.15.0
gyp ERR! node-gyp -v v4.0.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\builds\tc-workdir\DeepSpeech\ds\node_modules\node-gyp\bin\node-gyp.js configure --runtime=electron --target=5.0.13 --disturl=https://electronjs.org/headers --loglevel=verbose --module=C:\builds\tc-workdir\DeepSpeech\ds\native_client\javascript\lib\binding\v0.7.0-alpha.1\win32-x64\electron-v5.0\deepspeech.node --module_name=deepspeech --module_path=C:\builds\tc-workdir\DeepSpeech\ds\native_client\javascript\lib\binding\v0.7.0-alpha.1\win32-x64\electron-v5.0 --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=electron-v5.0' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\builds\tc-workdir\DeepSpeech\ds\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:915:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.3.9600
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\builds\\tc-workdir\\DeepSpeech\\ds\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "--runtime=electron" "--target=5.0.13" "--disturl=https://electronjs.org/headers" "rebuild" "--verbose"
node-pre-gyp ERR! cwd C:\builds\tc-workdir\DeepSpeech\ds\native_client\javascript
node-pre-gyp ERR! node -v v8.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
```

After some analysis and discussions, it was suggested that maybe some IPs / ranges from EC2 would get banned by your server for whatever reason and that this explains the issue. We (some other team, but also running on TaskCluster) have had that in the past with other projects, that banned for "abuse".

Could you please verify and tell us if there's some kind of IP-level or subnet-level ban in action that would account for those failures, and if so whether they can be lifted or we need to find some solution because that is abusing your resources ?

Thanks for any feedback!

**Comment by LuLuElayne** [comment]
Okay. So I’m clueless on what UR saying. All I know is my privacy is completely compromised by my roommate.(My sons father) I don’t know exactly what he can do but I know he reads & listens & possibly has video going on. He can probably read everything I’m saying even now. He writes code& is experienced. My Operating System on my last phone  was changed 2 a Custom Operating System . Which eventually stopped working properly. Can’t even reset it. I just want it 2 stop. And it’s against the law last I checked. I want 2 report it or get extra security or a person who can access my phone 2 figure it out. Please help me? I kkk no ow enough 2 know he’s hacked my phone. But not enough 2 intervene. Changing my passwords isn’t helpful at all. He just gets them anyway. Or uses a not authorized way. If U can help please text me or call me if allowed? 5309050713

**Comment by LuLuElayne** [comment]
I have a browser that GitHub can’t use. And I don’t know what it is or how to fix it.
