### ISSUE TITLE
[question] README?

### ISSUE THREAD

**Issue by harshkhandeparkar** [electron/electronjs.org#5550]
It seems like some apps' README file from the repo is displayed while it isn't for some. I also couldn't find a flag in the `.yml` file for this. Could someone explain what is happening here?

**Comment by vhashimotoo** [comment]
and it is not the right repo for this issue, the logs for the CI job is already having an answer:

```log
2021-07-20T12:07:04.4056579Z ten-hands: Non 404 error
2021-07-20T12:07:04.4058966Z RequestError [HttpError]: You have triggered an abuse detection mechanism. Please wait a few minutes before you try again.
2021-07-20T12:07:04.4062503Z     at /home/runner/work/apps/apps/app/node_modules/@octokit/request/dist-node/index.js:68:23
2021-07-20T12:07:04.4064571Z     at runMicrotasks (<anonymous>)
2021-07-20T12:07:04.4066827Z     at processTicksAndRejections (internal/process/task_queues.js:95:5) {
2021-07-20T12:07:04.4068754Z   status: 403,
2021-07-20T12:07:04.4069764Z   headers: {
2021-07-20T12:07:04.4071758Z     'access-control-allow-origin': '*',
2021-07-20T12:07:04.4079131Z     'access-control-expose-headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset',
2021-07-20T12:07:04.4085531Z     connection: 'close',
2021-07-20T12:07:04.4087331Z     'content-encoding': 'gzip',
2021-07-20T12:07:04.4114529Z     'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events translator.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com render-temp.githubusercontent.com viewscreen.githubusercontent.com; img-src 'self' data: github.githubassets.com media.githubusercontent.com camo.githubusercontent.com identicons.github.com collector.githubapp.com avatars.githubusercontent.com github-cloud.s3.amazonaws.com secured-user-images.githubusercontent.com/; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com",
2021-07-20T12:07:04.4139985Z     'content-type': 'application/json; charset=utf-8',
2021-07-20T12:07:04.4142226Z     date: 'Tue, 20 Jul 2021 12:07:02 GMT',
2021-07-20T12:07:04.4145045Z     'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
2021-07-20T12:07:04.4149219Z     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
2021-07-20T12:07:04.4152274Z     'retry-after': '60',
2021-07-20T12:07:04.4153884Z     server: 'GitHub.com',
2021-07-20T12:07:04.4156592Z     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
2021-07-20T12:07:04.4159348Z     'transfer-encoding': 'chunked',
2021-07-20T12:07:04.4161757Z     vary: 'Accept-Encoding, Accept, X-Requested-With',
2021-07-20T12:07:04.4164273Z     'x-content-type-options': 'nosniff',
2021-07-20T12:07:04.4166313Z     'x-frame-options': 'deny',
2021-07-20T12:07:04.4168482Z     'x-github-media-type': 'github.v3; format=json',
2021-07-20T12:07:04.4170976Z     'x-github-request-id': '0788:3EB2:53CB5E:D3A335:60F6BC66',
2021-07-20T12:07:04.4172997Z     'x-xss-protection': '0'
2021-07-20T12:07:04.4174126Z   },
2021-07-20T12:07:04.4175057Z   request: {
2021-07-20T12:07:04.4176630Z     method: 'GET',
2021-07-20T12:07:04.4179027Z     url: 'https://api.github.com/repos/saisandeepvaddi/ten-hands',
2021-07-20T12:07:04.4180926Z     headers: {
2021-07-20T12:07:04.4182822Z       accept: 'application/vnd.github.v3.html',
2021-07-20T12:07:04.4185670Z       'user-agent': 'octokit-rest.js/18.5.5 octokit-core.js/3.4.0 Node.js/14.17.3 (linux; x64)',
2021-07-20T12:07:04.4188302Z       authorization: 'token [REDACTED]'
2021-07-20T12:07:04.4189763Z     },
2021-07-20T12:07:04.4191115Z     request: { hook: [Function: bound bound register] }
2021-07-20T12:07:04.4192425Z   },
2021-07-20T12:07:04.4195990Z   documentation_url: 'https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#abuse-rate-limits'
2021-07-20T12:07:04.4198904Z }
```

**Comment by harshkhandeparkar** [comment]
Is the readme loaded on the server? Why not load it on the client-side to prevent ratelimits?

**Comment by vhashimotoo** [comment]
you already answered for own questions, the website never loads any remote content (except youtube). These errors come from the processor to give your that static readme property.

**Comment by harshkhandeparkar** [comment]
Umm, I didn't understand what you mean :sweat_smile:
